### ISSUE TITLE
`getdim` partial match functionality should no longer be default behaviour

### ISSUE THREAD

**Issue by dcalve** [met-office-ocean/CDFTOOLS#3]
The default partial dimension name matching for `getdim`:

https://github.com/met-office-ocean/CDFTOOLS/blob/993df9ea34c6dd38d3cd8120710fb124488a7c76/src/cdfio.F90#L835-L843

is incorrect behaviour for dimension names read from the namelist (`cn_x` etc). Since this covers the majority of `getdim` calls, I suggest that the default be changed to exact matching and that other calls use the partial matching.

**Comment by dcalve** [comment]
Fixed in #1.

The default behaviour for `getdim` is now exact name matching (`ldexact = true`). The partial matching has been left in the code as optional functionality, though no cases were apparent where this would be required.

**Comment by pmathiot** [comment]
You are write the line 
almost overwrite the variable lexact everywhere. 
I think this function could be useful for vertical dimension detht, depthu, deptv as in namelist we only have one dimension for the vertical. My preference is to set this to == 1, like this it deals fine with the temporary format we had x_grid_T/U/V.

Do you think:
comment line IF ( cdim_name == cn_x ) lexact=.true. 
set IF ( INDEX(clnam, TRIM(cdim_name)) /= 1 ) THEN instead of /=0

will do the job ? in case of partial match (all the case I face the begining was correct, and if perfect match it should also be 1.

**Comment by dcalve** [comment]
As we discussed, my current solution will not necessarily work for cdftools requiring files from multiple grids. 

I think the best solution is to search only the dimensions associated with the variable we are concerned with. We then have more confidence that an inexact match will return the correct dimension. This would require every `getdim` call to be passed a variable name however. 

A simpler, complimentary solution would be to instead return the *closest* match to the namelist dimension:

https://gist.github.com/dcalve/addbd180677beed434c7795aa63d4651 (possible errors)

The algorithm is simply to scan dimension names, compare them to the namelist dimension and use the dimension with the highest proportion of matching characters. This requires that the namelist dimension name be a substring of the intended match. If nothing is found with this method, then exit as normal.

Do we really want the `ldexact = true` case to use a `STOP`? This isn't done for other errors in `getdim`.

**Comment by dcalve** [comment]
Committed a first attempt at this (ab8637911713ca6097c65402ef74c52e9f13a4f1).

`ldexact` has been removed: the behaviour in all cases is now to first check for an exact name match and then a partial match if this fails. The method is obviously imperfect but it should do for now.

**Comment by dcalve** [comment]
I have run some tests on this and it seems to work as expected. I'll give an overview of the matching algorithm in case there are any comments.

Say `dim` is the namelist dimension name to be matched and `file_dim` is a dimension name in the netCDF file:

* First check for a `file_dim` exactly matching `dim` (previously `ldexact = true`)
* Otherwise, loop through all `file_dim` and find the closest partial match:
  * Check for `file_dim` that contain **all** characters in `dim`
    * The characters must match in the same order, but do not have to be contiguous
    * `depth` will match `deptht`, `tdepth` and `dep_th`
    * `depth300` will match `deptht300`
    * `depth` will not match `dep` or `z`
  * Return the matching `file_dim` with the smallest length
    * i.e. return the `file_dim` with the highest proportion of matching characters
    * `depth` will match `deptht` out of `deptht`, `deptht300`
* If no match was found, return `file_dim = "unknown"`

**Comment by pmathiot** [comment]
About the x and x_grid_T and axis_nbounds. Does your technique will work with a dimension name = x or should the dimension name need to be x_grid ? If I well understand with dim=x, it will pick file_dim=x_grid_T because this is the smallest file_dim name, isn't it ?

If yes, I am happy with this solution.

**Comment by dcalve** [comment]
`dim = x` will match `x` and `x_grid_T` instead of `axis_nbounds` for the standard and CMIP6 type of file. However I don't recommend using this `dim` as it will match the shortest dimension containing "x". It should be set to `dim = x` or `dim = x_grid` respectively.

Where `getdim` is applied to mesh mask files we should use a "try-except" style solution if necessary:

https://github.com/met-office-ocean/CDFTOOLS/blob/d798b6fc3bf88e0d1946363d108f09819328b24a/src/cdfio.F90#L1275-L1277

**Comment by dcalve** [comment]
Fixed as part of 5ec86c73a7ab757436d611445bcdaf32b0b1dab2
